### ISSUE TITLE
CSS - image jumps below image during transition

### ISSUE THREAD

**Issue by bikedel** [ragnarlotus/vue-flux#106]
Hello,

I am not sure if I need css or how to implement it. Below is the code I am using.

It all  works apart from during the transition the 'transition to image' is below the transition and when the transition is over it jumps back up into position.

Very nice work! Thank you

/*
<template>
  <div style="display: block; position: absoute">
    <q-card style="width: 800px; height: 600px">
      <VueFlux
        style="width: 800px; height: 600px"
        :transitions="transitions"
        :rscs="rscs"
        :options="options"
        ref="slider"
      >
        <template v-slot:preloader>
          <flux-preloader />
        </template>
      </VueFlux>
    </q-card>

    <button @click="$refs.slider.show('next')">NEXT</button>
  </div>
</template>

<style>
.FluxImage

</style>

<script setup>
import { ref, shallowReactive, onMounted } from "vue";
import {
  VueFlux,
  Img,
  Fade,
  Wave,
  Cube,
  Book,
  Waterfall,
  Swipe,
  Zip,
  Blinds2D,
  Kenburn,
  Blocks1,
  Warp,
  Explode,
  FluxControls,
  FluxIndex,
} from "vue-flux";

const mounted = ref(false);

const rscs = shallowReactive([
  new Img("images/f1.jpg"),
  new Img("images/f2.jpg"),
  new Img("images/s1.png"),
]);

const transitions = shallowReactive([Wave, Fade, Warp, Book]);

const options = shallowReactive({
  allowFullscreen: true,
  autoplay: true,
  bindKeys: true,
  infinite: true,
  controls: true,
  lazyLoadAfter: 10,
});

onMounted(() => {
  mounted.value = true;
});
</scrip>
*/

**Comment by ragnarlotus** [comment]
Yes, in your `main.js` or `main.ts` you need to import the CSS like this:

```js
import '../node_modules/vue-flux/dist/style.css';
```

Cheers and thanks for your words

**Comment by bikedel** [comment]
Hello

Thanks for the quick reply! Great it is working.
