### ISSUE TITLE
Not working in nuxt 3

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [ragnarlotus/vue-flux#109]
Please provide example to use in nuxt 3

**Comment by ragnarlotus** [comment]
Which vue-flux version are you using? probably you should use the alpha if nuxt 3 is using Vue 3

In any case I never used nuxt, so I can't provide it

**Comment by rahulkumarsingh73690** [comment]
I am using the alpha version. Windows is not defined error

**Comment by ragnarlotus** [comment]
are you using server side rendering? if so that could be the cause, try to exclude the slide from the SSR.

also without any error I can't help you

**Comment by rahulkumarsingh73690** [comment]
No SSR

**Comment by ragnarlotus** [comment]
check https://github.com/ragnarlotus/vue-flux/blob/v7/src/App.vue example about how to implement it

**Comment by rahulkumarsingh73690** [comment]
Let me check

**Comment by ragnarlotus** [comment]
try to implement the slider in empty project, without nuxt, if it does not work updaload it in a repo and I will take a look.

if it works in empty project but not in nuxt I could take a look when I have some free time, but I'm very busy now adding typescript and updating code architecture, so I can't promise you nothing
