### ISSUE TITLE
Slider with different delay

### ISSUE THREAD

**Issue by jeremyrncp** [ragnarlotus/vue-flux#110]
Hi, 

It's possible to make a slider with different delays between image ?

Best regards,
Jérémy

**Comment by ragnarlotus** [comment]
No sorry, but if you need you can control it using https://ragnarlotus.github.io/vue-flux-docs/v6/components/vue-flux.html#show-number-number-transition-string

**Comment by jeremyrncp** [comment]
Hi,

Thanks, it's possible to add this feature with fork repository ?

Best regards,
Jérémy

**Comment by ragnarlotus** [comment]
I'm not sure about what you ask me, sorry.

Can you give me more details?

**Comment by jeremyrncp** [comment]
Hi,

I need create slider with different delay by slide, as the transition.

Best regards,
Jérémy

**Comment by ragnarlotus** [comment]
I will add this feature for next stable version

**Comment by jeremyrncp** [comment]
Hi,

is it possible to help you achieve this feature? could you give me some tips to implement it ?

Best regards,
Jérémy

**Comment by ragnarlotus** [comment]
The implementation of typescript is really advanced, but now I have to start testing all components because I will have to fix some things.

The delay option would not come in the VueFluxOptions, but in `src/resources/Resource.ts` instead.

Past week I became father, so that limits me a lot the free time and unfortunatelly I can't give an ETA, depends on how much free gives me the baby 😄 

Feel free to check out the `v7` branch and test, fix, and send MR, I just pushed all changes I had in local.

Regards!

**Comment by jeremyrncp** [comment]
Hi,

Congratulations on this happy event, being a father is the best thing ever

I looked through resources.ts but I can't find the delay part.

Could you help me ?

Best regards,
Jérémy

**Comment by ragnarlotus** [comment]
Yeah, the delay per resource is not implemented yet, by now I implemented typescript and 95% is working again but still need to fix few things before adding the new features, you will be the first to know when I implement them 😁

**Comment by jeremyrncp** [comment]
Hi,

Thanks.

Were you able to continue the developments ?

Best regards,
Jérémy

**Comment by ragnarlotus** [comment]
Hello, yes, I've been developing further although before fixing the FluxGrid bug I had make changes in the architecture which were prioritary for the sense of readability and logic.

Next week I will be in holidays and next the kindergarten will begin so I expect to have more free time and speed up the release.

Regards!

**Comment by ragnarlotus** [comment]
Added to the latest alpha release, check App.vue in v7 branch to see how delay is passed.

Regards
