### ISSUE TITLE
want to use it in nuxt 3 version

### ISSUE THREAD

**Issue by jugol-kumar** [ragnarlotus/vue-flux#112]
hello brother, i want to use this package in nuxt 3. but i can't properly implement this package in nuxt 3. can you more explain and update your documentation for nuxt 3 version please.

**Comment by ragnarlotus** [comment]
Hello man, I'm currently working on updating the documentation... but VuePress -which is what I use for it- has updated to V2 so I'm still learning how to use it.

I didn't even test it in nuxt 3 but I think it should work and not differ so much from the previous version regarding the documentation at https://ragnarlotus.github.io/vue-flux-docs/v6/ssr-with-nuxt.html so basically telling nuxt to run that component in client and importing the CSS

By now you can take a look about how to use V7 at https://github.com/ragnarlotus/vue-flux/blob/v7/src/App.vue

Regards!

**Comment by ragnarlotus** [comment]
Hello, I don't know if you finally made it work, but the documentation is updated.

Regards
