### ISSUE TITLE
How destroy the object before unmount the vue-flux?

### ISSUE THREAD

**Issue by ARM-developer** [ragnarlotus/vue-flux#119]
I tried deleting the component with the reference but it didn't work.

![image](https://github.com/ragnarlotus/vue-flux/assets/47763448/56986212-9ea6-4a3e-9480-a8d1a747b443)

**Comment by ragnarlotus** [comment]
if you want to delete it without finishing the transhition:

``` js
const player = $vueFlux.value.getlayer();
await player.stop(true);
```

or...

setting the [emit](https://ragnarlotus.github.io/vue-flux-docs/documentation/v7/components/vue-flux#emits) `stop` to do whatever you want

``` js
$vueFlux.value.stop(true);
```
