### ISSUE TITLE
Problems handling different image sizes and aspect ratios

### ISSUE THREAD

**Issue by ppasler** [ragnarlotus/vue-flux#87]
Hey there,

we are using vue-flux in a light box (fullscreen) and have user input images.
So we can't ensure images are big enough to fill the whole space or have a certain aspect ratio. Both images can be in the same list.

Right now the small pictures are stretched to fit the space and also widescreen images are overflowing the view.

Is there a way to not stretch small images, but down scale large images to fit in the screen?

**Comment by deulos** [comment]
Hello, sorry for the late answer.

That is possible but not feasible, if you think about the behavior of animations, you will notice that the part of the image not covered will display what is behind, which will make it look odd...

But you gave me an idea... maybe I can set an option where you decide if the image should be stretched or scaled down and set a background color to fill the emptiness. Would it make sense to you?

Regards!

**Comment by lohithn4** [comment]
Hi, I was going through documentation for so long, to figure out this. since it is an enhancement, is there any workaround, at the present to make this happen.

**Comment by ragnarlotus** [comment]
Hello!, the only one, would be if you just have both images with exactly the same aspect ratio and filling the empty space with the color you want in the image that is not covering the whole canvas

**Comment by ragnarlotus** [comment]
Hello, it has rained a lot since you opened the issue and probably you will not need it now, but just to let you know that I didn't ignore you and I promised it has been implemented in the new version 🎉 

Regards
