### ISSUE TITLE
Book transition animation doesn't correspond to forward/backward buttons

### ISSUE THREAD

**Issue by bpossolo** [ragnarlotus/vue-flux#92]
I noticed this when using the book transition on my personal app but verified it's an issue in the demo too:
https://deulos.github.io/vue-flux-docs/demos/vue-flux/

to reproduce, unselect all the transitions except Book.
Click the back button (notice the page moves backwards properly).
Then click the forward button (notice the animation uses the backwards animation again).

uncheck then recheck the book animation checkbox
click the forward button (notice the page moves forward properly)
then click the back button (notice the animation uses the forward animation again)

**Comment by deulos** [comment]
Thanks, I will review it and let you now :)

**Comment by deulos** [comment]
You are dman right 😂 

I will create a fix version this week.

Thanks for reporting!

**Comment by bpossolo** [comment]
Awesome!

I took a quick look at the code hoping it was something I’d easily spot/fix but didn’t figure it out in the little time I had. I appreciate you jumping on it so quickly though!

**Comment by ragnarlotus** [comment]
It is already fixed :)

**Comment by bpossolo** [comment]
Awesome!! Thank you! I’ll pull it in tonight!

**Comment by bpossolo** [comment]
works perfect!
