### ISSUE TITLE
Overlay controls appear above navbar

### ISSUE THREAD

**Issue by hcphoon01** [ragnarlotus/vue-flux#93]
How can I fix this issue where my VueFlux controls appear over the top of my navbar?

![1FDN0ir](https://user-images.githubusercontent.com/31014269/98035597-aadf4100-1e10-11eb-901c-dbfbfa2d3836.png)

**Comment by deulos** [comment]
Hello, the complements use a css `z-index` `45` so just using a value above that for your navbar would be enough.

But if you want to be sure to be displayed also above every animation, use a `z-index` above 200 on your navbar.

Regards!
