### ISSUE TITLE
Undesired Image rotation

### ISSUE THREAD

**Issue by Audit-a-la-Carte** [ragnarlotus/vue-flux#96]
Hey,

I have been implementing the Vue-flux slider, using different photos (20-25+ on average per page). Really works like a charm, so compliments on job well done. I did notice some photos are rotated on display and it seems to be related to meta data of the picture?

Is there a way to override this behavior and just load them landscape as I intended?

Thanks,

**Comment by ragnarlotus** [comment]
Hello and thanks for your kind words!

The slider does nothing about the way the images are displayed, so probably is more like a browser feature... Try to open it and save it with another format, or maybe with a photo editor. In windows image viewer I know that you can rotate images and then are always displayed that way, it may be related and probably you are right about the metadata.

I'm sorry not being able to help you more but I don't really know much about image formats and metadata.

Regards!

**Comment by Audit-a-la-Carte** [comment]
Hi Ragnar,

Don't exactly know what happened, but after a rebuild of my files it seems to be resolved. Too bad I could not identify the root cause, as it was really nagging me ;)

Thanks for your reply though!

P
