### ISSUE TITLE
Index thumbnails don't follow aspectRatio option

### ISSUE THREAD

**Issue by malbrock** [ragnarlotus/vue-flux#97]
When setting aspectRatio option the main slider adapts to the specified ratio, however when Index is used, thumbnails stay on the default aspectRatio.

**Comment by ragnarlotus** [comment]
Hello! Sorry for the daly, I had a busy weekend las week.

But you can already update and will take into account the aspect ratio for the FluxIndex images 😁 

Let me know if you find any issue.

Regards!
