### ISSUE TITLE
app.js:31611 Uncaught (in promise) TypeError: Cannot read property '_c' of undefined

### ISSUE THREAD

**Issue by management-partners** [ragnarlotus/vue-flux#98]
i
![tem](https://user-images.githubusercontent.com/51586475/108005693-b4e22400-703c-11eb-8e66-f80a8a14049c.png)

<template>
  <div>
    <vue-flux
      :options="vfOptions"
      :images="vfImages"
      :transitions="vfTransitions"
      :captions="vfCaptions"
      ref="slider"
    >
      <template v-slot:preloader>
        <flux-preloader />
      </template>

      <template v-slot:caption>
        <flux-caption />
      </template>

      <template v-slot:controls>
        <flux-controls />
      </template>

      <template v-slot:pagination>
        <flux-pagination />
      </template>

      <template v-slot:index>
        <flux-index />
      </template>
    </vue-flux>

   
    </div>
  </div>
</template>

> 

<script>
import { data, computed } from "vue";
import {
  VueFlux,
  FluxCaption,
  FluxControls,
  FluxIndex,
  FluxPagination,
  FluxPreloader,
} from "vue-flux";
export default {
  name: "Home",
  components: {
    VueFlux,
    FluxCaption,
    FluxControls,
    FluxIndex,
    FluxPagination,
    FluxPreloader,
  },
  data: () => ({
    vfOptions: {
      autoplay: true,
    },
    vfTransitions: ["fade", "cube", "book", "wave"],
    vfImages: ["URL1", "URL2", "URL3"],
    vfCaptions: [
      "Caption for image 1",
      "Caption for image 2",
      "Caption for image 3",
    ],
  }),
  setup() {
    return {};
  },
};
</script>``

**Comment by ragnarlotus** [comment]
Hello, can you provide more info or full source code?

**Comment by midlantica** [comment]
Same issue. I think it's a Vue3 thing.

**Comment by ragnarlotus** [comment]
Thanks, I will try to take a look this weekend

**Comment by vasilkaptselau** [comment]
Hello!
Same problem. I try use code as component and put code inside of main.js but a problem same.

**Comment by ragnarlotus** [comment]
Vue 3 has lifecycle incompatibilities, but instead of trying to fix the current version I'm spending that time migrating the whole project to Vue 3.

And I still have some things to solve and test it well before release, so will take a while.

Sorry not being able to help you more 😓

**Comment by tarikkavaz** [comment]
hey @ragnarlotus did you had any chance?

**Comment by ragnarlotus** [comment]
Not yet sorry, still working in Vue 3, but will the new features and the differences with Vue 2 I had to do a big revamp in which I'm working when I have time. Most of the components already work, but still need to fix communication between them, the complements and other reactivities from controllers.

Sorry for the inconveniences

**Comment by githubissignedup** [comment]
@ragnarlotus  Thank you for helping us out. I am just raising my hand here in the queue. The libraries are marvellous.

**Comment by ragnarlotus** [comment]
Thanks for contacting, always cheers up knowing that people is using it and wants to continue doing so.

The new version is in advanced progress, just finishing the controllers and adjusting parameters and other stuff as you can see in https://github.com/ragnarlotus/vue-flux/tree/v7 

I wanted to release the v7 with new content like texts and videos but due to the complexity I will just leave it prepared and release it with full refactor and using vue3. if nothing blocks me I expect to have it ready within a month 🥳

**Comment by ragnarlotus** [comment]
An alpha version has been released, everything should be working, but further testing is required.

Regards

**Comment by ragnarlotus** [comment]
Hello! I'm pleased to announce that beta.1 has been released, 90% of documentation updated (only remains the complements and custom transitions)

Also added a section in documentation on how to use it if you use `Options` API

I consider this issue closed.

Thank you all who participated and cheered me up to continue with the project.

Regards to everyone and merry christmas!
